name: CI
on:
  #push:
   # branches: [ master ]
  #pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        set -x
        project=spring-petclinic
        compose=etc/docker/swarm/$project.yaml
        date=$( date +%s )
        script=.github/bin/check-service.sh
        sed -i s/worker/manager/ ${compose}
        sed -i s/secobau/${date}/ ${compose}
        docker swarm init
        docker build -t ${date}/$project --no-cache .
        docker stack deploy -c ${compose} $project
        chmod +x ${script}
        ./${script}
